language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: FsYdvy/lQxLx1YR7SkwFZuQs7/RlnrHON2TNfETTv3k7iGJFfR4HcA6p5W4mhy3BXgx15EnjOW67sVZ3i4HYmDH/kMQfXsEjXFn9zMk6y9HwQ/I250X4hSAxu9K8Gc70+eQ6M1zOIrd6bDsf/1tljI/OTsMUkOTWCc0oPsP61fSCYi3iJq8+DaGREYu4yweBFBQ5yG7eXWuzuaTw/KVTgK2Z/opLejb7fGFGRrOhSacwjLrLvFZ6mDQvIu1ev2Likzo3P3IhLr1kZfaSpEb6b9Z3si52dtCpVek75kVruj5bhvDqbWeKlmTkHK6KrtRElz8XytF3VeNHjCFHhqT9mYbfikM/ucpSNqqyXG+UARoCXKjQ07Q6eYl3OhqEBVt4mj15GCyNm6FHFFuLzIjb3yhw9/VVk60GcxDyoJTMLjEMv5XUx+0nzRTL3hxbVS2Ws+eFwOvtN7LqtTbENmzD0VlC7BSxd4PJEGuMGagUyg9mRJeu9MOwxL9AdNop/qQ13ZuLr2MEChbg461iJsOkI+xW21srhqT85YyW0xzzUd6+oSd0jKxD9F4DjIm34sEDhPBSm8LidYzOPJOaE0rgXQuvhnbkgDFn9lKMdDy/d6AHbrwQhF6/e6ljn1Y5VzaSb7506iAn7bOrvfUzJu+/b07+9aTF26NAo5hpMP/X/lI=
  app: desolate-earth-20215
  on:
    repo: drzoid14/node-shopping-list-integration-tests
