language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: UE862OIWRJpffG4lrkrmaT/yNyzb9IvZyxMIkEZ4rMyDZ2J6wZ4ZaamMyIzAnyWn4V+K0if019b+fNDiP7zPr91VXT8uYf91Y0N3pMBjmhEBC7BJ2fmaLidlaj5eaJzLGf/wq/VwX1VDv5mlJQHPT7XdN+fTZAlNvV//Q4VKQSUcYzY+Yk3qi1ylPNuf4OmWNSaJtWv83K2qwHTIzM0TNxvJANw5NGZwMlELHejp7Hj5yDYI0aSrX0OsQJ3uXTImc1MaLRJLsJpHn4xttuPalEU2xd0dAWJATW49dLlW61+/iuWK/9Kv5sfAKBw2VolMtlpN6RkTXT4jyLG2DldYoIGu71oFJjsFMKBRJK86jzsGKCECI+cNz8W4ruVbG4JevwSPjpkQ5cfHZev3dVoWP7pm7pk0l4heks/8AyvSLm3ZHb37tIOpT2s+b8NCO3sY7gnzNqIheSEsklgJ7sV0pkxHXJwFwhnp1UhiU8CtdR5R7rhFdGvWVKJc7yWkkWrMz5jfyN6d1udnGDW7fW88HsG953StBG8zo0asxImzus6LVsnAp1fot5vLQs6LAeQVGuNvm0Jmea1zHQmVxlv4oLMTDRIqrTiude8DM+HwJLeMDYWDxQU3ejfZ08Skq7ZK9cyBryd37I5rXu8l4DnXvwLWZyAoDzqKXbqAzU71khc=
  app: desolate-earth-20215
  on:
    repo: drzoid14/node-shopping-list-integration-tests
