language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: CUJEXBPJOv6c99Zg8H+28Yx1R1XrdXksnmZR7tO/RF0rU1Oo3l8k+8jHDWBJ033jhKWLs4QUo0CUxo4aAaYZWnLDO7og1bNkMZw/nK7zkXotiRD3WjwlaCXiTTjh59SlnWHd5g1mF8sC8sFXWMLgx8aAoAQVsvlWoLoF5dgqdbcloJMufIb5EcVgvsM0P9LtDX51Ed7e9InomeIyviliv5ByOihQJ1yxc/K1dtWILBGfJvDF5wijdEyuS9tv51EBW0H8nzgYCPUWyA/BLtMultm0anUl+lZGdWHHUX+IFvnSVDXNltJjxtI3/3xBphN3vYuINWcvfrZ83/qikcQ+tb6RXxXDI4ywP3KHRFbEfVZW/uUvpUSYhTO95+lvCJ3SWf3CgBulBwAZQ/7NoTp4N2nmLwiw1EvCcyQ7+IdmeV0ICJDfAxDrQUpgZG5r8jYMsKdxVned3MF2ynUPgJbQ6Pmenk9CPusGEukgMJzlF+joPPWUvxHiIS2Kt9lviUpWAdrNzS71notxGavw56PRvomUJFQvKN6uKy0jCoO1VfkkxXFZIThjPCcg+1p8iuno1xM9tY40jTVpVA7vqaYh8H5xnkWMTTUOLPw992Da23E6321CHuowb1ZVE+pNMq4YAGFNpc+qxKYE3Nf3wvMeeE+IE3P5xB7yj7AGgpt91+g=
  app: desolate-earth-20215
  on:
    repo: drzoid14/node-shopping-list-integration-tests
